
[[constraint]]
  name = "github.com/Shyp/go-git"
  version = "0.1.0"

[[constraint]]
  name = "github.com/kevinburke/rest"
  version = "2.0.0"

[[constraint]]
  name = "github.com/pelletier/go-toml"
  revision = "4692b8f9babfc93db58cc592ba2689d8736781de"

[[constraint]]
  name = "github.com/kevinburke/go-types"
  revision = "4297d3d97383038ce276d912d16de3eadeb7b521"

[prune]
  go-tests = true
  unused-packages = true
